const test=require('node:test'),assert=require('node:assert/strict'),ts=require('typescript'),fs=require('node:fs'),Module=require('node:module');const m=new Module(require('node:path').resolve('lib/attendance-save.ts'));m._compile(ts.transpileModule(fs.readFileSync(m.id,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,m.id);const {AttendanceSaveQueue}=m.exports;const tick=()=>new Promise(r=>setImmediate(r));
test('one row serializes rapid edits with updated revision',async()=>{let release;const calls=[];const q=new AttendanceSaveQueue(async(k,v,r)=>{calls.push([v.status,r]);if(calls.length===1)await new Promise(done=>release=done);return {record:{...v,revision:r+1}}},()=>{});q.seed('a',{status:null,notes:'',revision:0});q.enqueue('a',{status:'H',notes:''});q.enqueue('a',{status:'I',notes:'izin'});release();await tick();assert.deepEqual(calls,[['H',0],['I',1]]);assert.deepEqual(q.snapshot(),{})});
test('failed save is retained until explicit retry',async()=>{let fail=true;const states=[];const q=new AttendanceSaveQueue(async(k,v,r)=>{if(fail)throw Error('offline');return {record:{...v,revision:r+1}}},(k,s)=>states.push(s));q.seed('a',{status:null,notes:'',revision:0});q.enqueue('a',{status:'A',notes:''});await tick();assert.equal(q.snapshot().a.status,'A');fail=false;q.retry('a');await tick();assert.equal(states.at(-1),'saved')});
test('conflict stops writes until user chooses server or own values',async()=>{let calls=0;const server={status:'I',notes:'other writer',revision:5};const q=new AttendanceSaveQueue(async(k,v,r)=>{calls++;return calls===1?{conflict:true,record:server}:{record:{...v,revision:r+1}}},()=>{});q.seed('a',{status:null,notes:'',revision:0});q.enqueue('a',{status:'H',notes:''});await tick();assert.equal(calls,1);q.resolve('a',server,true);await tick();assert.equal(calls,2);assert.deepEqual(q.snapshot(),{})});

test('persisted pending edit retains its original revision for reconnect conflicts',async()=>{const q=new AttendanceSaveQueue(async()=>{throw Error('offline')},()=>{});q.seed('a',{status:null,notes:'',revision:2});q.enqueue('a',{status:'H',notes:''});await tick();assert.equal(q.snapshot().a.revision,2)});

test('online retry drains failed rows without resolving conflicts implicitly',async()=>{let online=false;const q=new AttendanceSaveQueue(async(k,v,r)=>{if(!online)throw Error('offline');return {record:{...v,revision:r+1}}},()=>{});q.seed('a',{status:null,notes:'',revision:0});q.enqueue('a',{status:'H',notes:''});await tick();online=true;q.retry();await tick();assert.deepEqual(q.snapshot(),{})});
test('one writer saving never erases another writer durable pending edits',()=>{const {attendancePendingKey,persistAttendancePending}=m.exports;const data=new Map();const storage={setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const a=attendancePendingKey('event','tab-a'),b=attendancePendingKey('event','tab-b');persistAttendancePending(storage,a,{one:{status:'H',notes:''}});persistAttendancePending(storage,b,{two:{status:'I',notes:'offline'}});persistAttendancePending(storage,a,{});assert.equal(JSON.parse(data.get(b)).two.notes,'offline');assert.equal(data.has(a),false)});
