begin;
do $$ declare uid uuid;token text:=encode(gen_random_bytes(32),'hex');lid uuid;begin
 insert into public.app_users(username,password_hash,role,display_name) values('__aeroo_qa_'||gen_random_uuid(),extensions.crypt('QA rollback password',extensions.gen_salt('bf',4)),'ADMIN','QA rollback') returning id into uid;
 insert into public.app_sessions(user_id,token_hash,expires_at) values(uid,encode(extensions.digest(token,'sha256'),'hex'),now()+interval '1 hour');
 perform set_config('request.headers',jsonb_build_object('x-aeroo-session',token)::text,true);
 select id into lid from public.levels where active order by sort_order limit 1;
 insert into public.classes(name,audience,level_id) values('__QA_CAB','CABERAWIT',lid),('__QA_PRIVATE','PENGURUS',null);
end $$;
do $$ declare lid uuid;begin select level_id into lid from public.classes where name='__QA_CAB';insert into public.classes(name,audience,level_id) values('__QA_CAB_NEW','CABERAWIT',lid);end $$;
set local role anon;
do $$ declare cat uuid;oldclass uuid;newclass uuid;lev uuid;p jsonb;pid uuid;mm jsonb;e jsonb;future_e jsonb;j jsonb;g jsonb;body jsonb;begin
 select id into cat from public.categories where slug='caberawit';select id,level_id into oldclass,lev from public.classes where name='__QA_CAB';select id into newclass from public.classes where name='__QA_CAB_NEW';
 p:=public.save_member(null,0,'{"name":"__QA Lifecycle"}',jsonb_build_array(jsonb_build_object('category_id',cat,'class_id',oldclass,'level_id',lev,'valid_from',current_date-1)));pid:=(p->>'id')::uuid;
 e:=public.ensure_attendance(jsonb_build_object('title','__QA history','event_date',current_date,'audience','CABERAWIT','class_id',oldclass,'level_id',lev));
 perform public.save_attendance_record((e->>'id')::uuid,pid,0,'H','history');
 j:=public.save_journal(null,0,jsonb_build_object('title','__QA Journal history','journal_kind','CABERAWIT_INDIVIDUAL','journal_date',current_date,'event_id',e->>'id','class_id',oldclass,'state','COMPLETED'),jsonb_build_array(jsonb_build_object('member_id',pid,'progress_value',80,'progress_note','preserved')));
 g:=public.save_agenda(null,0,jsonb_build_array(jsonb_build_object('title','__QA selected historical agenda','audience','CABERAWIT','starts_at',current_date::text||'T11:00:00+07:00','class_id',oldclass,'level_id',lev,'participant_ids',jsonb_build_array(pid))),'this');
 perform public.ensure_attendance(jsonb_build_object('agenda_id',g->0->>'id'));
 select to_jsonb(m) into mm from public.member_memberships m where member_id=pid and active;
 p:=public.save_member(pid,0,jsonb_build_object('name','__QA Lifecycle moved'),jsonb_build_array(mm||jsonb_build_object('class_id',newclass,'valid_from',current_date+7)));
 if not exists(select 1 from public.member_memberships where member_id=pid and class_id=oldclass and ended_on=current_date+7) then raise exception 'Future transition closes wrong date';end if;
 future_e:=public.ensure_attendance(jsonb_build_object('title','__QA before effective date','event_date',current_date,'audience','CABERAWIT','class_id',oldclass));
 if not exists(select 1 from public.attendance_records where event_id=(future_e->>'id')::uuid and participant_key=pid) then raise exception 'Current roster lost future transitioning person';end if;
 future_e:=public.ensure_attendance(jsonb_build_object('title','__QA after effective date','event_date',current_date+7,'audience','CABERAWIT','class_id',newclass));
 if not exists(select 1 from public.attendance_records where event_id=(future_e->>'id')::uuid and participant_key=pid) then raise exception 'Future roster missing transitioned person';end if;
 perform public.archive_member(pid,true);
 perform public.save_agenda((g->0->>'id')::uuid,0,'[{"status":"CANCELLED"}]','this');
 perform public.permanently_delete_member(pid);
 if not exists(select 1 from public.attendance_records where event_id=(e->>'id')::uuid and member_id is null and participant_key=pid and member_name_snapshot='__QA Lifecycle') then raise exception 'Permanent deletion lost roster snapshot';end if;
 if not exists(select 1 from public.journal_progress where journal_id=(j->>'id')::uuid and member_id is null and participant_key=pid and progress_value=80) then raise exception 'Permanent deletion lost assessment identity';end if;
 perform public.set_journal_state((j->>'id')::uuid,0,'ARCHIVED');
 perform public.set_journal_state((j->>'id')::uuid,1,'DRAFT');
 if (select count(*) from public.journal_progress where journal_id=(j->>'id')::uuid)<>1 then raise exception 'Archive/restore deleted assessment';end if;
 perform public.save_learning_target(jsonb_build_object('title','__QA manual target','level_id',lev,'target_month',current_date));
 select to_jsonb(row_j) into body from public.journals row_j where id=(j->>'id')::uuid;
 perform public.save_journal((j->>'id')::uuid,2,body||'{"state":"COMPLETED"}',jsonb_build_array(jsonb_build_object('member_id',pid,'progress_value',80,'progress_note','historical edit retained')));
end $$;
select 'PASS: effective dates, historical cancellation, permanent deletion, journal archive and restore' as result;
rollback;
