begin;
do $$ declare uid uuid;token text:=encode(gen_random_bytes(32),'hex');lid uuid;begin
 insert into public.app_users(username,password_hash,role,display_name) values('__aeroo_qa_'||gen_random_uuid(),extensions.crypt('QA rollback password',extensions.gen_salt('bf',4)),'ADMIN','QA rollback') returning id into uid;
 insert into public.app_sessions(user_id,token_hash,expires_at) values(uid,encode(extensions.digest(token,'sha256'),'hex'),now()+interval '1 hour');
 perform set_config('request.headers',jsonb_build_object('x-aeroo-session',token)::text,true);
 select id into lid from public.levels where active order by sort_order limit 1;
 insert into public.classes(name,audience,level_id) values('__QA_CAB','CABERAWIT',lid),('__QA_PRIVATE','PENGURUS',null);
end $$;
set local role anon;
do $$ declare person jsonb;v_member uuid;cat uuid;ibu uuid;klass uuid;private_klass uuid;lev uuid;event jsonb;changed jsonb;journal jsonb;agenda jsonb;revision integer;ms jsonb;blocked boolean;target jsonb;login_count integer;qa_username text;begin
 select id into cat from public.categories where slug='caberawit';select id into ibu from public.categories where slug='ibu-ibu';select id,level_id into klass,lev from public.classes where name='__QA_CAB';select id into private_klass from public.classes where name='__QA_PRIVATE';
 person:=public.save_member(null,0,'{"name":"__QA Person","phone":"PRIVATE_PHONE","address":"PRIVATE_ADDRESS"}',jsonb_build_array(jsonb_build_object('category_id',cat,'class_id',klass,'level_id',lev,'valid_from','2026-01-01')));v_member:=(person->>'id')::uuid;
 event:=public.ensure_attendance(jsonb_build_object('title','__QA Attendance','event_date',current_date,'audience','CABERAWIT','class_id',klass,'level_id',lev));
 if not exists(select 1 from public.attendance_records where event_id=(event->>'id')::uuid and member_id=v_member and status is null) then raise exception 'QA pending roster missing';end if;
 if (public.ensure_attendance(jsonb_build_object('title','__QA Attendance','event_date',current_date,'audience','CABERAWIT','class_id',klass,'level_id',lev))->>'id')<>event->>'id' then raise exception 'QA idempotent session failed';end if;
 changed:=public.save_attendance_record((event->>'id')::uuid,v_member,0,'H','first');
 if (changed->'record'->>'revision')::int<>1 then raise exception 'QA save revision failed';end if;
 if not(public.save_attendance_record((event->>'id')::uuid,v_member,0,'A','stale')->>'conflict')::boolean then raise exception 'QA stale write accepted';end if;
 blocked:=false;begin perform public.save_attendance_record((event->>'id')::uuid,v_member,null,'A','null');exception when others then blocked:=true;end;if not blocked then raise exception 'QA null revision accepted';end if;
 blocked:=false;begin perform public.ensure_attendance(jsonb_build_object('title','__QA bad','event_date',current_date,'audience','CABERAWIT','class_id',private_klass));exception when others then blocked:=true;end;if not blocked then raise exception 'QA cross audience class accepted';end if;
 blocked:=false;begin perform public.save_member(null,0,'{"name":"__QA Invalid"}',jsonb_build_array(jsonb_build_object('category_id',ibu,'class_id',klass)));exception when others then blocked:=true;end;if not blocked then raise exception 'QA ibu learning accepted';end if;
 select jsonb_agg(to_jsonb(m)) into ms from public.member_memberships m where m.member_id=v_member and active;
 person:=public.save_member(v_member,0,'{"name":"__QA Person Updated"}',ms);
 if (select count(*) from public.member_memberships where member_id=v_member)<>1 then raise exception 'QA biodata edit duplicates history';end if;
 blocked:=false;begin perform public.save_member(v_member,0,'{"name":"__QA stale"}',ms);exception when others then blocked:=true;end;if not blocked then raise exception 'QA stale biodata accepted';end if;
 journal:=public.save_journal(null,0,jsonb_build_object('journal_kind','CABERAWIT_INDIVIDUAL','journal_date',current_date,'event_id',event->>'id','class_id',klass,'title','__QA Journal','state','COMPLETED','assessment','{}'::jsonb),jsonb_build_array(jsonb_build_object('member_id',v_member,'target_id',null,'progress_value',null,'progress_note','not assessed')));
 if (journal->>'state')<>'COMPLETED' then raise exception 'QA journal failed';end if;
 changed:=public.save_attendance_record((event->>'id')::uuid,v_member,1,'I','absent');
 blocked:=false;begin perform public.save_journal(null,0,jsonb_build_object('journal_kind','CABERAWIT_INDIVIDUAL','journal_date',current_date,'event_id',event->>'id','class_id',klass,'title','__QA invalid Journal','state','COMPLETED'),jsonb_build_array(jsonb_build_object('member_id',v_member,'progress_value',50)));exception when others then blocked:=true;end;if not blocked then raise exception 'QA absent student assessed';end if;
 agenda:=public.save_agenda(null,0,jsonb_build_array(jsonb_build_object('title','__QA Agenda','audience','CABERAWIT','starts_at',current_date::text||'T09:00:00+07:00','ends_at',current_date::text||'T10:00:00+07:00','class_id',klass,'level_id',lev)),'this');
 event:=public.ensure_attendance(jsonb_build_object('agenda_id',agenda->0->>'id'));
 perform public.save_agenda((agenda->0->>'id')::uuid,0,'[{"status":"CANCELLED"}]','this');
 if not exists(select 1 from public.attendance_events where id=(event->>'id')::uuid and state='CANCELLED') then raise exception 'QA cancellation not linked';end if;
 target:=public.import_target_version(jsonb_build_object('title','__QA Targets','period_start',current_date,'period_end',current_date),jsonb_build_array(jsonb_build_object('level_id',lev,'class_id',klass,'title','__QA target','target_month',date_trunc('month',current_date)::date)));
 if (target->>'inserted')::integer<>1 then raise exception 'QA target version import failed';end if;
 blocked:=false;begin perform public.import_target_version('{}',jsonb_build_array(jsonb_build_object('level_id',lev,'class_id',private_klass,'title','__QA private target','target_month',date_trunc('month',current_date)::date)));exception when others then blocked:=true;end;if not blocked then raise exception 'QA target private class accepted';end if;
 if public.archive_member(v_member,true)->>'status'<>'INACTIVE' then raise exception 'QA archive failed';end if;
 if public.archive_member(v_member,false)->>'status'<>'ACTIVE' then raise exception 'QA restore failed';end if;
 select username into qa_username from public.get_current_app_user();
 select count(*) into login_count from public.login_app_audited(qa_username,'wrong',null,'QA');if login_count<>0 then raise exception 'QA invalid password accepted';end if;
 select count(*) into login_count from public.login_app_audited(qa_username,null,null,'QA');if login_count<>0 then raise exception 'QA null password accepted';end if;
 select count(*) into login_count from public.login_app_audited(qa_username,'QA rollback password',null,'QA');if login_count<>1 then raise exception 'QA correct login failed';end if;
 if not exists(select 1 from public.login_history where username=qa_username and not success) then raise exception 'QA failed login audit missing';end if;
 if public.viewer_data('members')::text like '%PRIVATE_%' then raise exception 'QA private biodata leaked';end if;
 perform set_config('request.headers','{}',true);
 if exists(select 1 from public.members) then raise exception 'QA raw members visible publicly';end if;
 if public.viewer_data('classes')::text like '%__QA_PRIVATE%' then raise exception 'QA private class leaked';end if;
 blocked:=false;begin perform public.save_member(null,0,'{"name":"__QA anonymous"}',ms);exception when others then blocked:=true;end;if not blocked then raise exception 'QA anonymous write accepted';end if;
end $$;
select 'PASS: roster, revisions, scope, journal eligibility, cancellation and public privacy' as result;
rollback;
