const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript'),vm=require('vm');
function load(file){if(!fs.existsSync(file))return {};let m={exports:{}};vm.runInNewContext(ts.transpile(fs.readFileSync(file,'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}),{exports:m.exports,module:m,require,Date,Map,Set});return m.exports;}
const d=load('lib/domain.ts');
test('unassessed progress remains unknown, actual zero is assessed',()=>{assert.equal(typeof d.summarizeProgress,'function');assert.equal(d.summarizeProgress(['a'],[]).percentage,null);let r=d.summarizeProgress(['a','b'],[{target_id:'a',progress_value:0}]);assert.equal(r.assessed,1);assert.equal(r.percentage,0)});
test('latest target revision wins and unrelated target excluded',()=>{assert.equal(typeof d.summarizeProgress,'function');const r=d.summarizeProgress(['a','b'],[{target_id:'a',progress_value:20,created_at:'2026-01-01'},{target_id:'a',progress_value:80,created_at:'2026-01-02'},{target_id:'x',progress_value:100}]);assert.equal(r.percentage,80);assert.equal(r.assigned,2);assert.equal(r.assessed,1)});
test('pending attendance is separate from Alfa',()=>{assert.equal(typeof d.summarizeAttendance,'function');let r=d.summarizeAttendance([{status:'H'},{status:null},{status:'A'},{status:'I'}]);assert.equal(r.pending,1);assert.equal(r.A,1);assert.equal(r.percentage,33.3)});
test('recurrence preserves Jakarta clock, monthly avoids overflowing date',()=>{assert.equal(typeof d.recurrenceDates,'function');assert.deepEqual(Array.from(d.recurrenceDates('2026-01-31','monthly','2026-04-30')),['2026-01-31','2026-02-28','2026-03-31','2026-04-30']);assert.deepEqual(Array.from(d.recurrenceDates('2026-10-05','weekly','2026-10-19')),['2026-10-05','2026-10-12','2026-10-19'])});

test('clearing latest assessment does not resurrect prior score',()=>{assert.equal(d.summarizeProgress(['a'],[{target_id:'a',progress_value:null,created_at:'2026-02-01'},{target_id:'a',progress_value:90,created_at:'2026-01-01'}]).percentage,null)});
test('invalid dates return false without throwing',()=>{assert.equal(d.validDate('2026-99-01'),false);assert.equal(d.validDate('2026-02-30'),false)});
test('progress follows meeting chronology when an older journal is edited',()=>{assert.equal(d.summarizeProgress(['a'],[{target_id:'a',progress_value:10,journal_date:'2026-01-01',created_at:'2026-02-01'},{target_id:'a',progress_value:90,journal_date:'2026-01-10',created_at:'2026-01-10'}]).percentage,90)});

test("membership is selected by effective dates including a scheduled transition",()=>{const {effectiveMembership}=d;assert.equal(effectiveMembership({active:false,valid_from:"2026-01-01",valid_to:"2026-10-11",ended_on:"2026-10-12"},"2026-10-05"),true);assert.equal(effectiveMembership({active:true,valid_from:"2026-10-12"},"2026-10-05"),false);assert.equal(effectiveMembership({active:true,valid_from:"2026-10-12"},"2026-10-12"),true)});
