'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
type Note={id:string;owner_user_id:string;title:string;content:string;status:string;is_pinned:boolean;revision:number;updated_at:string};
export default function Notes(){
 const[rows,setRows]=useState<Note[]>([]),[draft,setDraft]=useState<Note|null>(null),[status,setStatus]=useState('ACTIVE'),[query,setQuery]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[loading,setLoading]=useState(true);
 const current=useRef<Note|null>(null),pending=useRef(false),busy=useRef(false),conflict=useRef(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/notes?status='+status,{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);setRows(data);for(const n of data){try{const stored=JSON.parse(sessionStorage.getItem('airo-note-draft:'+n.id)||'null');if(stored?.owner_user_id===n.owner_user_id&&!current.current){current.current=stored;setDraft(stored);pending.current=true;setDirty(true);break}}catch{}}}catch(e){setError(e instanceof Error?e.message:'Gagal memuat.')}finally{setLoading(false)}},[status]);
 useEffect(()=>{void load()},[load]);
 const quickCreated=useRef(false);
 useEffect(()=>{if(quickCreated.current||new URLSearchParams(window.location.search).get('create')!=='1'||loading)return;quickCreated.current=true;void create()},[loading]);
 const flush=useCallback(async()=>{if(busy.current||!pending.current||!current.current||conflict.current)return;busy.current=true;setSaving(true);setError('');try{while(pending.current&&current.current){pending.current=false;const sent:Note={...current.current};const r:Response=await fetch('/api/notes/'+sent.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(sent)});const saved:Note&{error?:string}=await r.json();if(!r.ok){pending.current=true;conflict.current=r.status===409;throw Error(r.status===409?'Catatan berubah di perangkat lain. Salin tulisan Anda sebelum memuat ulang.':saved.error)}if(current.current?.id===saved.id){current.current={...current.current,revision:saved.revision,updated_at:saved.updated_at};setDraft({...current.current});setRows(v=>v.map(x=>x.id===saved.id?saved:x).filter(x=>x.status===status));}}if(current.current)sessionStorage.removeItem('airo-note-draft:'+current.current.id);setDirty(false)}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan.')}finally{busy.current=false;setSaving(false)}},[status]);
 useEffect(()=>{if(!dirty)return;const t=setTimeout(()=>void flush(),650);return()=>clearTimeout(t)},[draft,dirty,flush]);
 useEffect(()=>{const navigate=async(e:MouseEvent)=>{const link=(e.target as Element)?.closest?.('a[href]') as HTMLAnchorElement|null;if(!link||(!pending.current&&!busy.current)||e.ctrlKey||e.metaKey||link.target==='_blank')return;e.preventDefault();e.stopPropagation();await flush();if(!pending.current&&!busy.current)window.location.href=link.href};document.addEventListener('click',navigate,true);const warn=(e:BeforeUnloadEvent)=>{if(pending.current||busy.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);const online=()=>void flush();window.addEventListener('online',online);return()=>{document.removeEventListener('click',navigate,true);window.removeEventListener('beforeunload',warn);window.removeEventListener('online',online)}},[flush]);
 function edit(values:Partial<Note>){if(!current.current)return;current.current={...current.current,...values};pending.current=true;try{sessionStorage.setItem('airo-note-draft:'+current.current.id,JSON.stringify(current.current))}catch{setError('Penyimpanan perangkat tidak tersedia. Jangan tutup sebelum tersimpan.')}setDirty(true);setDraft({...current.current})}
 async function select(n:Note){await flush();if(pending.current||busy.current)return;conflict.current=false;let recovered:Note|null=null;try{const stored=JSON.parse(sessionStorage.getItem('airo-note-draft:'+n.id)||'null');if(stored?.id===n.id&&stored.owner_user_id===n.owner_user_id)recovered=stored}catch{}current.current=recovered||{...n};setDraft({...current.current});setError('');if(recovered){pending.current=true;setDirty(true);void flush()}}
 async function create(){await flush();if(pending.current||busy.current)return;setSaving(true);try{const r=await fetch('/api/notes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'Catatan baru',content:''})});const n=await r.json();if(!r.ok)throw Error(n.error);setStatus('ACTIVE');setRows(v=>[n,...v]);current.current=n;setDraft(n);conflict.current=false}catch(e){setError(e instanceof Error?e.message:'Gagal membuat.')}finally{setSaving(false)}}
 return <><div className="pageHeader"><h1>Catatan</h1><button className="btn" disabled={saving||dirty} onClick={()=>void create()}>+ Catatan</button></div><div className="toolbar"><input aria-label="Cari catatan" className="input" placeholder="Cari catatan" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Status catatan" className="select" value={status} disabled={dirty||saving} onChange={e=>{setStatus(e.target.value);setDraft(null);current.current=null}}><option value="ACTIVE">Aktif</option><option value="ARCHIVED">Arsip</option><option value="DELETED">Sampah</option></select></div>{error&&<div role="alert" className="notice error">{error}<button className="smallAction" onClick={()=>void flush()}>Coba simpan</button></div>}<div className="notesLayout section"><section className="noteList">{loading?<div className="card">Memuat…</div>:rows.filter(n=>(n.title+' '+n.content).toLowerCase().includes(query.toLowerCase())).map(n=><button className={'noteItem '+(draft?.id===n.id?'selected':'')} key={n.id} onClick={()=>void select(n)} disabled={saving}><strong>{n.is_pinned?'📌 ':''}{n.title}</strong><span>{n.content.slice(0,100)||'Kosong'}</span><small>{new Date(n.updated_at).toLocaleDateString('id-ID')}</small></button>)}{!loading&&!rows.length&&<div className="emptyState">Belum ada catatan.</div>}</section>{draft?<section className="card noteEditor"><div className="row between"><span role="status">{saving?'Menyimpan…':dirty?'Belum tersimpan':'Tersimpan'}</span><button className="smallAction" onClick={()=>edit({is_pinned:!draft.is_pinned})}>{draft.is_pinned?'Lepas sematan':'Sematkan'}</button></div><input aria-label="Judul catatan" className="input" maxLength={200} value={draft.title} onChange={e=>edit({title:e.target.value})}/><textarea aria-label="Isi catatan" className="textarea" maxLength={100000} value={draft.content} onChange={e=>edit({content:e.target.value})}/><div className="row"><button className="smallAction" onClick={()=>{edit({status:draft.status==='ARCHIVED'||draft.status==='DELETED'?'ACTIVE':'ARCHIVED'});void flush()}}>{draft.status==='ACTIVE'?'Arsipkan':'Pulihkan'}</button>{draft.status!=='DELETED'&&<button className="smallAction danger" onClick={()=>{edit({status:'DELETED'});void flush()}}>Pindahkan ke sampah</button>}</div></section>:<div className="emptyState">Pilih catatan.</div>}</div></>
}
