import JSZip from 'jszip';
export const escapeXml=(value:unknown)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const decode=(s:string)=>s.replace(/&#(x[0-9a-f]+|[0-9]+);/gi,(_,n)=>{const value=n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):Number(n);return value>0&&value<=0x10ffff?String.fromCodePoint(value):'�'}).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');
/** Replace only text within one paragraph; distribute deletions across existing runs. */
export function replaceReportXml(xml:string,values:Record<string,string>){
 return xml.replace(/<(a|w):p\b[^>]*>[\s\S]*?<\/\1:p>/g,paragraph=>{
  const nodes=Array.from(paragraph.matchAll(/<(a|w):t\b[^>]*>([\s\S]*?)<\/\1:t>/g));
  const texts=nodes.map(n=>decode(n[2]));const joined=texts.join('');const edits=Array.from(joined.matchAll(/\{\{([A-Z_]+)\}\}/g)).filter(n=>Object.hasOwn(values,n[1]));
  if(!edits.length)return paragraph;
  for(const edit of edits.reverse()){const start=edit.index!,end=start+edit[0].length;let offset=0;for(let i=0;i<texts.length;i++){const originalLength=decode(nodes[i][2]).length;const a=Math.max(0,start-offset),b=Math.min(originalLength,end-offset);if(b>a)texts[i]=texts[i].slice(0,a)+(start>=offset&&start<offset+originalLength?values[edit[1]]:'')+texts[i].slice(b);offset+=originalLength;}}
  let i=0;return paragraph.replace(/(<(?:a|w):t\b[^>]*>)[\s\S]*?(<\/(?:a|w):t>)/g,(_,open,close)=>open+escapeXml(texts[i++])+close);
 });
}
export async function validateOfficeTemplate(bytes:Uint8Array,kind:string){
 if(!['pptx','docx'].includes(kind)||bytes.length>8*1024*1024)throw new Error('Template tidak valid atau melebihi 8 MB.');
 const zip=await JSZip.loadAsync(bytes,{checkCRC32:false});const entries=Object.values(zip.files);if(entries.length>1000)throw new Error('Terlalu banyak bagian dalam template.');
 let total=0;for(const entry of entries){const size=(entry as unknown as {_data?:{uncompressedSize?:number}})._data?.uncompressedSize??0;total+=size;if(size>16*1024*1024||total>32*1024*1024)throw new Error('Isi template terlalu besar.');if(/vbaProject|activeX|embeddings/i.test(entry.name))throw new Error('Template mengandung konten aktif yang tidak didukung.');}
 if(!zip.file('[Content_Types].xml')||!zip.file('_rels/.rels')||!zip.file(kind==='pptx'?'ppt/presentation.xml':'word/document.xml'))throw new Error('Isi file bukan dokumen Office yang sesuai.');
 for(const entry of entries.filter(e=>/\.(xml|rels)$/.test(e.name))){const text=await entry.async('string');if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('Deklarasi XML tidak didukung.');if(entry.name.endsWith('.rels')&&/TargetMode\s*=\s*["']External["']/i.test(text))throw new Error('Tautan eksternal dalam template tidak didukung.');}
 return zip;
}
export type ReportSlide={title:string;lines:string[]};
export async function defaultPresentation(slides:ReportSlide[]){
 const z=new JSZip();const p='http://schemas.openxmlformats.org/presentationml/2006/main',a='http://schemas.openxmlformats.org/drawingml/2006/main',r='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
 const rels=(items:string)=>`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${items}</Relationships>`;
 z.file('[Content_Types].xml',`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>${slides.map((_,i)=>`<Override PartName="/ppt/slides/slide${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join('')}</Types>`);
 z.file('_rels/.rels',rels(`<Relationship Id="rId1" Type="${r}/officeDocument" Target="ppt/presentation.xml"/>`));
 z.file('ppt/presentation.xml',`<p:presentation xmlns:p="${p}" xmlns:a="${a}" xmlns:r="${r}"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="master"/></p:sldMasterIdLst><p:sldIdLst>${slides.map((_,i)=>`<p:sldId id="${256+i}" r:id="rId${i+1}"/>`).join('')}</p:sldIdLst><p:sldSz cx="12192000" cy="6858000"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>`);
 z.file('ppt/_rels/presentation.xml.rels',rels(`<Relationship Id="master" Type="${r}/slideMaster" Target="slideMasters/slideMaster1.xml"/>`+slides.map((_,i)=>`<Relationship Id="rId${i+1}" Type="${r}/slide" Target="slides/slide${i+1}.xml"/>`).join('')));
 const tree='<p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree>';
 z.file('ppt/slideMasters/slideMaster1.xml',`<p:sldMaster xmlns:p="${p}" xmlns:a="${a}" xmlns:r="${r}"><p:cSld>${tree}</p:cSld><p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/><p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="layout"/></p:sldLayoutIdLst><p:txStyles/></p:sldMaster>`);
 z.file('ppt/slideMasters/_rels/slideMaster1.xml.rels',rels(`<Relationship Id="layout" Type="${r}/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>`));
 z.file('ppt/slideLayouts/slideLayout1.xml',`<p:sldLayout xmlns:p="${p}" xmlns:a="${a}" xmlns:r="${r}" type="blank" preserve="1"><p:cSld name="Blank">${tree}</p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`);
 z.file('ppt/slideLayouts/_rels/slideLayout1.xml.rels',rels(`<Relationship Id="master" Type="${r}/slideMaster" Target="../slideMasters/slideMaster1.xml"/>`));
 const types=await z.file('[Content_Types].xml')!.async('string');z.file('[Content_Types].xml',types.replace('</Types>','<Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/></Types>'));
 slides.forEach((slide,i)=>{z.file(`ppt/slides/_rels/slide${i+1}.xml.rels`,rels(`<Relationship Id="layout" Type="${r}/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>`));const paragraphs=[slide.title,...slide.lines].map((line,j)=>`<a:p><a:r><a:rPr lang="id-ID" sz="${j===0?3200:1800}"${j===0?' b="1"':''}/><a:t>${escapeXml(line)}</a:t></a:r><a:endParaRPr lang="id-ID"/></a:p>`).join('');z.file(`ppt/slides/slide${i+1}.xml`,`<p:sld xmlns:p="${p}" xmlns:a="${a}" xmlns:r="${r}"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="Laporan"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="600000" y="400000"/><a:ext cx="10900000" cy="5900000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/></p:spPr><p:txBody><a:bodyPr wrap="square"/><a:lstStyle/>${paragraphs}</p:txBody></p:sp></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`);});
 return z.generateAsync({type:'uint8array'});
}
/** Include all report detail pages even when the uploaded design only contains a cover. */
export async function appendReportDetails(zip:JSZip,kind:string,slides:ReportSlide[]){
 if(kind==='docx'){const file=zip.file('word/document.xml');if(!file)return;const xml=await file.async('string');const detail=slides.map(s=>[s.title,...s.lines].map(line=>`<w:p><w:r><w:t xml:space="preserve">${escapeXml(line)}</w:t></w:r></w:p>`).join('')).join('');zip.file('word/document.xml',xml.replace(/(<w:sectPr\b|<\/w:body>)/,detail+'$1'));return;}
 const generated=await JSZip.loadAsync(await defaultPresentation(slides));let presentation=await zip.file('ppt/presentation.xml')!.async('string');const relPath='ppt/_rels/presentation.xml.rels';let relationships=await zip.file(relPath)!.async('string');let index=Math.max(0,...Object.keys(zip.files).map(p=>Number(p.match(/^ppt\/slides\/slide(\d+)\.xml$/)?.[1]??0)));let id=Math.max(255,...Array.from(presentation.matchAll(/<p:sldId\b[^>]*\bid="(\d+)"/g),m=>Number(m[1])));let types=await zip.file('[Content_Types].xml')!.async('string');
 const existingSlideRels=Object.keys(zip.files).find(path=>/^ppt\/slides\/_rels\/slide\d+\.xml\.rels$/.test(path));const layoutRel=existingSlideRels?(await zip.file(existingSlideRels)!.async('string')).match(/<Relationship\b[^>]*Type="[^"]*\/slideLayout"[^>]*\/>/)?.[0]:null;
 for(let i=0;i<slides.length;i++){index++;id++;if(layoutRel)zip.file(`ppt/slides/_rels/slide${index}.xml.rels`,`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${layoutRel}</Relationships>`);const relId=`aerooDetail${index}`;zip.file(`ppt/slides/slide${index}.xml`,await generated.file(`ppt/slides/slide${i+1}.xml`)!.async('string'));presentation=presentation.replace('</p:sldIdLst>',`<p:sldId id="${id}" r:id="${relId}"/></p:sldIdLst>`);relationships=relationships.replace('</Relationships>',`<Relationship Id="${relId}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${index}.xml"/></Relationships>`);types=types.replace('</Types>',`<Override PartName="/ppt/slides/slide${index}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/></Types>`);}
 zip.file('ppt/presentation.xml',presentation);zip.file(relPath,relationships);zip.file('[Content_Types].xml',types);
}
