import {NextRequest,NextResponse} from 'next/server';
import * as XLSX from 'xlsx';
import {db} from '@/lib/supabase-server';
import {publicRows} from '@/lib/public-read';
import {excelDate,spreadsheetCell,readWorkbook} from '@/lib/spreadsheet';
export const runtime='nodejs';
const columns=['ID Anggota','Revision','Nama','Jenis Kelamin','Tempat Lahir','Tanggal Lahir','Nomor HP','Alamat','Jenjang','Kelas','Bagian Pengurus','Kategori (pisahkan koma)','Catatan','Nama Wali','Nomor HP Wali','Keikutsertaan JSON'];
const norm=(v:unknown)=>String(v??'').trim();
function workbook(rows:unknown[][],name:string){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(rows),'Anggota');return new Response(XLSX.write(book,{type:'buffer',bookType:'xlsx'}),{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="${name}"`}})}
export async function GET(req:NextRequest){try{
 if(req.nextUrl.searchParams.get('template')==='1')return workbook([columns,['','','Contoh Nama','L','Malang','2010-01-01','08123456789','Alamat lengkap','SD 1','','','Caberawit, Kelompok','','','','']], 'template-anggota-airo.xlsx');
 const s=await db();const{data:role}=await s.rpc('current_app_role');const viewer=!role||role==='VIEWER';const result=viewer?{data:await publicRows('members'),error:null}:await s.from('members').select('*,member_memberships(*,categories(name,slug),classes(name),levels(name))').eq('status','ACTIVE').order('name');if(result.error)throw Error(result.error.message);
 const rows:unknown[][]=viewer?[['ID Anggota','Nama','Kategori','Jenjang','Kelas'],...(result.data||[]).map((p:any)=>[p.id,p.name,p.member_categories.map((m:any)=>m.categories?.name).join(', '),p.member_memberships.map((m:any)=>m.levels?.name).filter(Boolean).join(', '),p.member_memberships.map((m:any)=>m.classes?.name).filter(Boolean).join(', ')])]:[columns,...(result.data||[]).map((p:any)=>{const mm=p.member_memberships.filter((m:any)=>m.active);const learning=mm.find((m:any)=>['caberawit','muda-mudi'].includes(m.categories?.slug));return [p.id,p.revision,p.name,p.gender,p.birth_place,p.birth_date,p.phone,p.address,learning?.levels?.name,learning?.classes?.name,mm.find((m:any)=>m.categories?.slug==='pengurus')?.section,mm.map((m:any)=>m.categories?.name).join(', '),p.notes,p.guardian_name,p.guardian_phone,JSON.stringify(mm.map(({categories,classes,levels,created_at,member_id,...m}:any)=>m))]})];
 if(req.nextUrl.searchParams.get('format')==='csv')return new Response('\ufeff'+rows.map(r=>r.map(v=>'"'+spreadsheetCell(v).replace(/"/g,'""')+'"').join(',')).join('\r\n'),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="anggota-airo.csv"'}});return workbook(rows,'anggota-airo.xlsx');
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Export gagal'},{status:400})}}
export async function POST(req:NextRequest){try{
 const s=await db();const{data:role}=await s.rpc('current_app_role');if(!['ADMIN','DEWAN_GURU','KELOMPOK'].includes(role||''))return NextResponse.json({error:'Akses input ditolak.'},{status:403});const {data:me}=await s.rpc('get_current_app_user');const owner=me?.[0];const form=await req.formData();const file=form.get('file');if(!(file instanceof File))throw Error('Pilih workbook');const book=await readWorkbook(file);const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(book.Sheets[book.SheetNames[0]],{defval:''});if(!rows.length||rows.length>500)throw Error('Isi 1–500 anggota per impor');const {data:job}=owner?await s.from('import_jobs').insert({owner_user_id:owner.id,resource_type:'ANGGOTA',file_name:file.name,status:'VALIDATING',total_rows:rows.length}).select('id').single():{data:null};
 const [catRes,levelRes,classRes,existingRes]=await Promise.all([s.from('categories').select('id,name,slug'),s.from('levels').select('id,name'),s.from('classes').select('id,name,level_id,audience'),s.from('members').select('id,name,birth_date,phone,address,gender,member_categories(category_id)')]);if(catRes.error||levelRes.error||classRes.error||existingRes.error)throw Error('Referensi impor tidak dapat dimuat');const cats=catRes.data||[],levels=levelRes.data||[],classes=classRes.data||[];const payload:any[]=[];const errors:string[]=[];const seen=new Set<string>();
 for(let i=0;i<rows.length;i++){try{const row=rows[i],name=norm(row.Nama);if(!name)throw Error('Nama kosong');const birth_date=excelDate(row['Tanggal Lahir']);const categoryNames=norm(row['Kategori (pisahkan koma)']).split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);const selected=categoryNames.map(n=>cats.find(c=>c.name.toLowerCase()===n||c.slug===n));const className=norm(row.Kelas),levelName=norm(row.Jenjang);const klass=className?classes.filter(k=>k.name.toLowerCase()===className.toLowerCase()):[];if(!norm(row['Keikutsertaan JSON'])&&className&&klass.length!==1)throw Error('Kelas tidak ditemukan atau namanya ambigu');const level=levelName?levels.find(l=>l.name.toLowerCase()===levelName.toLowerCase()):null;if(!norm(row['Keikutsertaan JSON'])&&levelName&&!level)throw Error('Jenjang tidak ditemukan');let memberships:any[];
 if(norm(row['Keikutsertaan JSON'])){memberships=JSON.parse(norm(row['Keikutsertaan JSON']));if(!Array.isArray(memberships))throw Error('JSON keikutsertaan harus berupa daftar')}
 else{if(className&&!selected.some(c=>c&&klass[0]?.audience===(c.slug==='caberawit'?'CABERAWIT':c.slug==='muda-mudi'?'MUDA_MUDI':'')))throw Error('Kelas tidak sesuai kategori yang dipilih');if(!selected.length||selected.some(c=>!c))throw Error('Kategori tidak valid');memberships=selected.map(c=>({category_id:c!.id,active:true,...(['caberawit','muda-mudi'].includes(c!.slug)?{class_id:klass[0]?.audience===(c!.slug==='caberawit'?'CABERAWIT':'MUDA_MUDI')?klass[0]?.id:null,level_id:klass[0]?.audience===(c!.slug==='caberawit'?'CABERAWIT':'MUDA_MUDI')?klass[0]?.level_id||level?.id:level?.id}:c!.slug==='pengurus'?{section:norm(row['Bagian Pengurus'])}:{})}))}
 const id=norm(row['ID Anggota'])||null;const person={name,gender:norm(row['Jenis Kelamin']),birth_place:norm(row['Tempat Lahir']),birth_date,phone:norm(row['Nomor HP']),address:norm(row.Alamat),notes:norm(row.Catatan),guardian_name:norm(row['Nama Wali']),guardian_phone:norm(row['Nomor HP Wali'])};const fingerprint=JSON.stringify([name.toLowerCase(),birth_date,person.phone,person.address,person.gender,memberships.map(m=>m.category_id).sort()]);if(seen.has(id||fingerprint))throw Error('Baris duplikat di workbook');seen.add(id||fingerprint);if(!id&&existingRes.data?.some(p=>JSON.stringify([p.name.toLowerCase(),p.birth_date,p.phone||'',p.address||'',p.gender||'',p.member_categories.map(c=>c.category_id).sort()])===fingerprint))throw Error('Biodata identik sudah ada. Gunakan ID Anggota untuk memperbarui; nama tidak digabung otomatis.');if(id&&(!Number.isInteger(Number(row.Revision))||norm(row.Revision)===''))throw Error('Revision wajib untuk memperbarui ID Anggota');payload.push({id,revision:id?Number(row.Revision):0,person,memberships});
 }catch(e){errors.push(`Baris ${i+2}: ${e instanceof Error?e.message:'Data tidak valid'}`)}}
 if(errors.length){if(job?.id)await s.from('import_jobs').update({status:'FAILED',error_rows:errors.length,errors,completed_at:new Date().toISOString()}).eq('id',job.id);return NextResponse.json({error:'Impor dibatalkan; perbaiki semua baris terlebih dahulu.',errors},{status:400})}if(job?.id)await s.from('import_jobs').update({status:'IMPORTING'}).eq('id',job.id);const{data,error}=await s.rpc('save_members_batch',{p_rows:payload});if(error){if(job?.id)await s.from('import_jobs').update({status:'FAILED',error_rows:1,errors:[error.message],completed_at:new Date().toISOString()}).eq('id',job.id);return NextResponse.json({error:error.message},{status:error.message.includes('CONFLICT')?409:400})}const inserted=payload.filter(p=>!p.id).length,updated=payload.filter(p=>p.id).length;if(job?.id)await s.from('import_jobs').update({status:'COMPLETED',inserted_rows:inserted,updated_rows:updated,completed_at:new Date().toISOString()}).eq('id',job.id);return NextResponse.json({inserted,updated,processed:data,errors:[]});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Workbook tidak dapat dibaca.'},{status:400})}}
