'use client';
import {FormEvent,useEffect,useState} from 'react';
import {jakartaDate} from '@/lib/domain';
type Position={id?:string;revision:number;member_id:string;title:string;section:string;duties:string;valid_from:string;valid_to:string|null;active:boolean;members?:{name:string}};
const empty=():Position=>({revision:0,member_id:'',title:'',section:'',duties:'',valid_from:jakartaDate(),valid_to:'',active:true});
export default function Structure(){const[rows,setRows]=useState<Position[]>([]),[people,setPeople]=useState<Array<{id:string;name:string}>>([]),[form,setForm]=useState<Position|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[history,setHistory]=useState(false);
 async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch('/api/positions'),fetch('/api/members')]);const p=await a.json(),m=await b.json();if(!a.ok||!b.ok)throw Error(p.error||m.error);setRows(p);setPeople(m);setError('')}catch(e){setError(e instanceof Error?e.message:'Gagal memuat.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);try{const r=await fetch('/api/positions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const v=await r.json();if(!r.ok)throw Error(v.error);setForm(null);await load()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan.')}finally{setSaving(false)}}
 const current=(p:Position)=>p.active&&p.valid_from<=jakartaDate()&&(!p.valid_to||p.valid_to>=jakartaDate());const change=(k:string,v:string)=>setForm(p=>p?{...p,[k]:v}:p);
 return <><div className="pageHeader"><h1>Struktur & Pengurus</h1><button className="btn" onClick={()=>setForm(empty())}>+ Jabatan</button></div><div className="tabBar"><button className={!history?'tab active':'tab'} onClick={()=>setHistory(false)}>Aktif</button><button className={history?'tab active':'tab'} onClick={()=>setHistory(true)}>Riwayat</button></div>{error&&<div className="notice error" role="alert">{error}</div>}<div className="structureGrid section">{loading?<div className="card">Memuat…</div>:rows.filter(p=>history||current(p)).map(p=><article className="card" key={p.id}><span className="badge">{p.section||'Pengurus'}</span><h2 className="section">{p.title}</h2><strong>{p.members?.name||'Anggota'}</strong><p>{p.duties}</p><small>{p.valid_from} — {p.valid_to||'Sekarang'}</small><div className="section"><button className="smallAction" onClick={()=>setForm({...p})}>Edit</button></div></article>)}</div>{!loading&&!rows.filter(p=>history||current(p)).length&&<div className="emptyState">Belum ada jabatan.</div>}{form&&<div className="dialogBackdrop" onClick={()=>!saving&&setForm(null)}><form role="dialog" aria-modal="true" aria-labelledby="position-title" className="dialogCard" onSubmit={save} onClick={e=>e.stopPropagation()}><div className="cardHead"><h2 id="position-title">{form.id?'Edit Jabatan':'Jabatan Baru'}</h2><button type="button" className="smallAction" disabled={saving} onClick={()=>setForm(null)}>Tutup</button></div><label>Anggota<select autoFocus className="select" required disabled={!!form.id} value={form.member_id} onChange={e=>change('member_id',e.target.value)}><option value="">Pilih anggota</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{(['title','section','duties','valid_from','valid_to'] as const).map(k=><label key={k}>{{title:'Jabatan',section:'Bidang',duties:'Tugas',valid_from:'Mulai menjabat',valid_to:'Akhir menjabat'}[k]}<input className="input" type={k.startsWith('valid_')?'date':'text'} required={k==='title'||k==='valid_from'} readOnly={!!form.id&&k==='valid_from'} value={form[k]||''} onChange={e=>change(k,e.target.value)}/></label>)}<div className="formActions"><button className="btn" disabled={saving}>{saving?'Menyimpan…':'Simpan'}</button></div></form></div>}</>
}
