import {NextRequest,NextResponse} from 'next/server';import {dataSummary} from '@/lib/public-read';import {db} from '@/lib/supabase-server';import {reportRows} from '@/lib/rebuild';import * as XLSX from 'xlsx';import {Document,Packer,Paragraph,Table,TableRow,TableCell} from 'docx';import {jsPDF} from 'jspdf';import {defaultPresentation} from '@/lib/report-template';
export const runtime='nodejs';
export async function GET(req:NextRequest){try{const snapshot=req.nextUrl.searchParams.get('snapshot');let d:any;if(snapshot){const s=await db();const {data,error}=await s.from('report_snapshots').select('dataset').eq('id',snapshot).single();if(error)throw Error('Versi laporan tidak ditemukan.');d=data.dataset}else d=await dataSummary(req);const rows=reportRows(d);const format=req.nextUrl.searchParams.get('format')||'xlsx';if(format==='json')return NextResponse.json(d);const title='Simpul — Rekap '+d.month;let bytes:Uint8Array|ArrayBuffer;let mime:string;
 if(format==='xlsx'){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.summary),'Ringkasan');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.individuals),'Individu');bytes=XLSX.write(wb,{type:'array',bookType:'xlsx'});mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}
 else if(format==='docx'){const table=(records:any[])=>new Table({rows:[new TableRow({children:Object.keys(records[0]||{}).map(k=>new TableCell({children:[new Paragraph(k)]}))}),...records.map(r=>new TableRow({children:Object.values(r).map(v=>new TableCell({children:[new Paragraph(String(v))]}))}))]});bytes=new Uint8Array(await Packer.toBuffer(new Document({sections:[{children:[new Paragraph({text:title,heading:'Heading1'}),new Paragraph('Periode '+d.span+' bulan'),table(rows.summary),new Paragraph({text:'Individu',heading:'Heading2'}),...(rows.individuals.length?[table(rows.individuals)]:[new Paragraph('Belum ada data.')])]}]})));mime='application/vnd.openxmlformats-officedocument.wordprocessingml.document'}
 else if(format==='pptx'){bytes=await defaultPresentation([{title,lines:rows.summary.map(x=>x.Indikator+': '+x.Jumlah)},...Array.from({length:Math.ceil(rows.individuals.length/8)},(_,i)=>({title:'Presensi individu',lines:rows.individuals.slice(i*8,i*8+8).map((p:any)=>`${p.Nama} | H ${p.Hadir} · I ${p.Izin} · A ${p.Alfa} · Belum ${p['Belum absen']}`)}))]);mime='application/vnd.openxmlformats-officedocument.presentationml.presentation'}
 else if(format==='pdf'){const pdf=new jsPDF();let y=18;const line=(text:string)=>{const ls=pdf.splitTextToSize(text,180);for(const l of ls){if(y>278){pdf.addPage();y=18}pdf.text(l,14,y);y+=7}};pdf.setFontSize(15);line('Simpul - Rekap '+d.month);pdf.setFontSize(11);line('Periode '+d.span+' bulan');rows.summary.forEach(r=>line(r.Indikator+': '+r.Jumlah));y+=6;rows.individuals.forEach((p:any)=>line(`${p.Nama} | H ${p.Hadir}, I ${p.Izin}, A ${p.Alfa}, Belum ${p['Belum absen']}`));bytes=pdf.output('arraybuffer');mime='application/pdf'}
 else return NextResponse.json({error:'Format tidak didukung.'},{status:400});return new Response(bytes as BodyInit,{headers:{'Content-Type':mime,'Content-Disposition':`attachment; filename="simpul-rekap-${d.month}.${format}"`,'Cache-Control':'no-store'}})
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Gagal membuat laporan.'},{status:400})}}
