import {NextRequest,NextResponse} from 'next/server';
import {db} from '@/lib/supabase-server';
import {writeScopesForRole} from '@/lib/access';
import {slugByAudience} from '@/lib/domain';
export async function POST(req:NextRequest){try{
 const s=await db();const{data:role}=await s.rpc('current_app_role');if(!writeScopesForRole(role).length)return NextResponse.json({error:'Akses ditolak.'},{status:403});const body=await req.json();const ids=[...new Set<string>(body.member_ids||[])];if(!ids.length||ids.length>500||(!(body.category_ids||[]).length&&!body.class_id))throw Error('Pilih maksimal 500 anggota dan tujuan');const[{data:people,error},{data:cats},{data:klass}]=await Promise.all([s.from('members').select('*,member_memberships(*,categories(slug))').in('id',ids),s.from('categories').select('id,slug'),body.class_id?s.from('classes').select('*').eq('id',body.class_id).single():Promise.resolve({data:null})]);if(error)throw Error(error.message);if(people?.length!==ids.length)throw Error('Sebagian anggota tidak ditemukan atau di luar akses');
 const rows=people.map(p=>{let memberships=p.member_memberships.filter((m:any)=>m.active&&writeScopesForRole(role).some(a=>slugByAudience[a]===m.categories?.slug));for(const category_id of body.category_ids||[]){if(!memberships.some((m:any)=>m.category_id===category_id))memberships.push({category_id,active:true})}if(klass){const category=cats?.find(c=>c.slug===slugByAudience[klass.audience]);if(!category||!memberships.some((m:any)=>m.category_id===category.id))throw Error('Anggota belum mengikuti kategori kelas tujuan');memberships=memberships.map((m:any)=>m.category_id===category.id?{...m,class_id:klass.id,level_id:klass.level_id}:m)}return {id:p.id,revision:p.revision,person:p,memberships}});
 const{data,error:save}=await s.rpc('save_members_batch',{p_rows:rows});return save?NextResponse.json({error:save.message},{status:save.message.includes('CONFLICT')?409:400}):NextResponse.json({updated:data,added:0});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Perubahan gagal.'},{status:400})}}
