create or replace function public.ensure_attendance(p_event jsonb) returns jsonb language plpgsql security definer set search_path='' set row_security=off as $$
declare e public.attendance_events%rowtype;g public.agenda%rowtype;a public.audience_type;v_key text;v_slug text;v_date date;v_class uuid;v_level uuid;v_activity uuid;v_people uuid[]:='{}';begin
 if nullif(p_event->>'agenda_id','') is not null then select * into g from public.agenda where id=(p_event->>'agenda_id')::uuid;
 if not found or g.status='CANCELLED' or not g.attendance_enabled then raise exception 'Agenda tidak dapat diabsen';end if;
 v_class:=g.class_id;v_level:=g.level_id;v_activity:=g.activity_type_id;v_people:=g.participant_ids;
 a:=g.audience;v_date:=(g.starts_at at time zone 'Asia/Jakarta')::date;v_key:='agenda:'||g.id;
 else v_class:=nullif(p_event->>'class_id','')::uuid;v_level:=nullif(p_event->>'level_id','')::uuid;v_activity:=nullif(p_event->>'activity_type_id','')::uuid;
 if p_event->'member_ids' is not null and jsonb_typeof(p_event->'member_ids')<>'array' then raise exception 'Daftar peserta tidak valid';end if;
 select coalesce(array_agg(distinct value::uuid order by value::uuid),'{}') into v_people from jsonb_array_elements_text(coalesce(p_event->'member_ids','[]'));
 a:=(p_event->>'audience')::public.audience_type;v_date:=(p_event->>'event_date')::date;
 v_key:=a||':'||v_date||':'||coalesce(p_event->>'class_id','')||':'||coalesce(p_event->>'level_id','')||':'||coalesce(p_event->>'event_time','')||':'||lower(trim(p_event->>'title'))||':'||array_to_string(v_people,',');end if;
 if not coalesce(public.can_write_audience(a),false) then raise exception 'Kegiatan di luar akses';end if;
 if a is null or v_date is null then raise exception 'Kategori dan tanggal wajib diisi';end if;
 if v_class is not null and not exists(select 1 from public.classes where id=v_class and audience=a and active and (v_level is null or level_id=v_level)) then raise exception 'Kelas tidak sesuai kategori atau jenjang';end if;
 if v_level is not null and (a not in ('CABERAWIT','MUDA_MUDI') or not exists(select 1 from public.levels where id=v_level and active)) then raise exception 'Jenjang tidak sesuai kategori';end if;
 if v_activity is not null and not exists(select 1 from public.activity_types where id=v_activity and audience=a and active) then raise exception 'Jenis kegiatan tidak sesuai kategori';end if;
 if v_class is not null and v_level is null then select level_id into v_level from public.classes where id=v_class;end if;
 if g.id is null and length(trim(coalesce(p_event->>'title','')))=0 then raise exception 'Judul kegiatan wajib diisi';end if;
 if g.id is null then v_key:=a||':'||v_date||':'||coalesce(v_class::text,'')||':'||coalesce(v_level::text,'')||':'||coalesce(v_activity::text,'')||':'||coalesce(p_event->>'event_time','')||':'||lower(trim(p_event->>'title'))||':'||array_to_string(v_people,',');end if;
 perform pg_advisory_xact_lock(hashtextextended(v_key,0));
 select * into e from public.attendance_events where session_key=v_key;
 if not found then
 insert into public.attendance_events(title,event_date,event_time,audience,activity_type_id,class_id,level_id,agenda_id,session_key,notes)
 values(coalesce(g.title,p_event->>'title'),v_date,coalesce((g.starts_at at time zone 'Asia/Jakarta')::time,nullif(p_event->>'event_time','')::time),a,v_activity,v_class,v_level,g.id,v_key,p_event->>'notes') returning * into e;
 v_slug:=case a when 'KELOMPOK' then 'kelompok' when 'CABERAWIT' then 'caberawit' when 'MUDA_MUDI' then 'muda-mudi' when 'IBU_IBU' then 'ibu-ibu' when 'PENGURUS' then 'pengurus' end;
 insert into public.attendance_records(event_id,member_id,participant_key,status,member_name_snapshot,class_id_snapshot,level_id_snapshot,class_name_snapshot,level_name_snapshot)
 select distinct on(m.id) e.id,m.id,m.id,null,m.name,mm.class_id,mm.level_id,c.name,l.name
 from public.members m join public.member_memberships mm on mm.member_id=m.id join public.categories cat on cat.id=mm.category_id left join public.classes c on c.id=mm.class_id left join public.levels l on l.id=mm.level_id
 where (m.status='ACTIVE' or v_date<(m.updated_at at time zone 'Asia/Jakarta')::date) and (mm.active or mm.valid_to is not null) and cat.slug=v_slug and mm.valid_from<=v_date and (mm.valid_to is null or mm.valid_to>=v_date)
 and (e.class_id is null or mm.class_id=e.class_id) and (e.level_id is null or mm.level_id=e.level_id)
 and (cardinality(v_people)=0 or m.id=any(v_people)) order by m.id,mm.created_at desc;
 end if;
 return to_jsonb(e);
end $$;
create or replace function public.viewer_data(p_resource text) returns jsonb language plpgsql stable security definer set search_path='' set row_security=off as $$
declare v jsonb;begin
 case p_resource
 when 'members' then select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'name',m.name,'status',m.status,'class_id',m.class_id,'level_id',m.level_id,'classes',jsonb_build_object('name',c.name),'levels',jsonb_build_object('name',l.name),
 'member_categories',(select coalesce(jsonb_agg(jsonb_build_object('category_id',cat.id,'categories',jsonb_build_object('id',cat.id,'name',cat.name,'slug',cat.slug))),'[]') from public.member_categories mc join public.categories cat on cat.id=mc.category_id where mc.member_id=m.id and cat.slug<>'pengurus'),
 'member_memberships',(select coalesce(jsonb_agg(jsonb_build_object('category_id',mm.category_id,'class_id',mm.class_id,'level_id',mm.level_id,'active',mm.active,'valid_from',mm.valid_from,'valid_to',mm.valid_to,'categories',jsonb_build_object('name',cat.name,'slug',cat.slug),'classes',jsonb_build_object('name',cl.name),'levels',jsonb_build_object('name',le.name))),'[]') from public.member_memberships mm join public.categories cat on cat.id=mm.category_id left join public.classes cl on cl.id=mm.class_id left join public.levels le on le.id=mm.level_id where mm.member_id=m.id and cat.slug<>'pengurus' and mm.active)) order by m.name),'[]') into v from public.members m left join public.classes c on c.id=m.class_id left join public.levels l on l.id=m.level_id where m.status='ACTIVE' and exists(select 1 from public.member_categories mc join public.categories cat on cat.id=mc.category_id where mc.member_id=m.id and cat.slug<>'pengurus');
 when 'classes' then select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'audience',c.audience,'level_id',c.level_id,'levels',jsonb_build_object('name',l.name)) order by c.name),'[]') into v from public.classes c left join public.levels l on l.id=c.level_id where c.active and c.audience<>'PENGURUS';
 when 'levels' then select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) order by sort_order),'[]') into v from public.levels where active;
 when 'categories' then select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'slug',slug)),'[]') into v from public.categories where slug<>'pengurus';
 when 'attendance' then select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'title',e.title,'event_date',e.event_date,'event_time',e.event_time,'audience',e.audience,'class_id',e.class_id,'level_id',e.level_id,'agenda_id',e.agenda_id,'state',e.state,'classes',jsonb_build_object('name',c.name),'attendance_records',(select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'member_id',r.member_id,'participant_key',r.participant_key,'member_name_snapshot',r.member_name_snapshot,'status',r.status,'class_id_snapshot',r.class_id_snapshot,'class_name_snapshot',r.class_name_snapshot,'level_id_snapshot',r.level_id_snapshot,'level_name_snapshot',r.level_name_snapshot)),'[]') from public.attendance_records r where r.event_id=e.id)) order by e.event_date desc),'[]') into v from public.attendance_events e left join public.classes c on c.id=e.class_id where e.audience<>'PENGURUS';
 when 'agenda' then select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'title',g.title,'starts_at',g.starts_at,'ends_at',g.ends_at,'audience',g.audience,'status',g.status,'presenter',g.presenter,'location',g.location,'class_id',g.class_id,'level_id',g.level_id,'attendance_enabled',g.attendance_enabled,'activity_type_id',g.activity_type_id,'activity_types',jsonb_build_object('name',a.name)) order by starts_at),'[]') into v from public.agenda g left join public.activity_types a on a.id=g.activity_type_id where g.audience<>'PENGURUS';
 when 'journals' then select coalesce(jsonb_agg(jsonb_build_object('id',j.id,'event_id',j.event_id,'journal_date',j.journal_date,'journal_kind',j.journal_kind,'title',j.title,'material',j.material,'summary',j.summary,'achievement',j.achievement,'state',j.state,'class_id',j.class_id,'member_id',j.member_id,'classes',jsonb_build_object('name',c.name),'members',jsonb_build_object('name',m.name),'assessment',jsonb_build_object('materials',coalesce(j.assessment->'materials','[]'::jsonb))) order by journal_date desc),'[]') into v from public.journals j left join public.classes c on c.id=j.class_id left join public.members m on m.id=j.member_id where j.state='COMPLETED' and j.journal_kind<>'PENGURUS' and (j.event_id is null or exists(select 1 from public.attendance_events e where e.id=j.event_id and e.audience<>'PENGURUS' and e.state<>'CANCELLED')) and (j.activity_type_id is null or exists(select 1 from public.activity_types a where a.id=j.activity_type_id and a.audience<>'PENGURUS'));
 when 'targets' then select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'title',t.title,'code',t.code,'target_month',t.target_month,'class_id',t.class_id,'level_id',t.level_id,'version_id',t.version_id,'target_value',t.target_value,'target_unit',t.target_unit,'levels',jsonb_build_object('name',l.name),'classes',jsonb_build_object('name',c.name))),'[]') into v from public.learning_targets t left join public.levels l on l.id=t.level_id left join public.classes c on c.id=t.class_id where t.active;
 when 'versions' then select coalesce(jsonb_agg(jsonb_build_object('id',id,'title',title,'version',version,'period_start',period_start,'period_end',period_end,'created_at',created_at) order by created_at desc),'[]') into v from public.target_versions;
 when 'progress' then select coalesce(jsonb_agg(jsonb_build_object('member_id',p.member_id,'target_id',p.target_id,'progress_value',p.progress_value,'created_at',p.created_at,'journal_date',j.journal_date)),'[]') into v from public.journal_progress p join public.journals j on j.id=p.journal_id where j.state='COMPLETED' and j.journal_kind in ('CABERAWIT_INDIVIDUAL','MUDA_MUDI_INDIVIDUAL') and (j.event_id is null or exists(select 1 from public.attendance_events e join public.attendance_records r on r.event_id=e.id where e.id=j.event_id and e.state<>'CANCELLED' and r.member_id=p.member_id and r.status='H'));
 when 'activity-types' then select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'audience',audience)),'[]') into v from public.activity_types where active and audience<>'PENGURUS';
 when 'report-templates' then v:='[]'::jsonb;
 else raise exception 'Projection non disponible';end case;return v;
end $$;
revoke all on function public.viewer_data(text) from public;grant execute on function public.viewer_data(text) to anon,authenticated;

drop policy journal_progress_read on public.journal_progress;
create policy journal_progress_read on public.journal_progress for select to anon,authenticated using(exists(select 1 from public.journals j where j.id=journal_id and public.can_read_audience(public.journal_audience(j.journal_kind)) and (j.event_id is null or exists(select 1 from public.attendance_events e join public.attendance_records r on r.event_id=e.id where e.id=j.event_id and e.state<>'CANCELLED' and r.member_id=journal_progress.member_id and r.status='H'))));
