create or replace function public.viewer_data(p_resource text) returns jsonb language plpgsql stable security definer set search_path='' set row_security=off as $$
declare v jsonb;begin
 case p_resource
 when 'members' then select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'name',m.name,'status',m.status,'class_id',placement.class_id,'level_id',placement.level_id,'classes',jsonb_build_object('name',c.name),'levels',jsonb_build_object('name',l.name),
 'member_categories',(select coalesce(jsonb_agg(jsonb_build_object('category_id',cat.id,'categories',jsonb_build_object('id',cat.id,'name',cat.name,'slug',cat.slug))),'[]') from public.member_memberships mc join public.categories cat on cat.id=mc.category_id where mc.member_id=m.id and cat.slug<>'pengurus' and mc.valid_from<=(now() at time zone 'Asia/Jakarta')::date and (mc.ended_on is null or mc.ended_on>(now() at time zone 'Asia/Jakarta')::date) and (mc.valid_to is null or mc.valid_to>=(now() at time zone 'Asia/Jakarta')::date)),
 'member_memberships',(select coalesce(jsonb_agg(jsonb_build_object('category_id',mm.category_id,'class_id',mm.class_id,'level_id',mm.level_id,'active',(mm.valid_from<=(now() at time zone 'Asia/Jakarta')::date and (mm.valid_to is null or mm.valid_to>=(now() at time zone 'Asia/Jakarta')::date) and (mm.ended_on is null or mm.ended_on>(now() at time zone 'Asia/Jakarta')::date)),'valid_from',mm.valid_from,'valid_to',mm.valid_to,'categories',jsonb_build_object('name',cat.name,'slug',cat.slug),'classes',jsonb_build_object('name',cl.name),'levels',jsonb_build_object('name',le.name))),'[]') from public.member_memberships mm join public.categories cat on cat.id=mm.category_id left join public.classes cl on cl.id=mm.class_id left join public.levels le on le.id=mm.level_id where mm.member_id=m.id and cat.slug<>'pengurus')) order by m.name),'[]') into v from public.members m left join lateral(select mm.class_id,mm.level_id from public.member_memberships mm join public.categories cat on cat.id=mm.category_id where mm.member_id=m.id and cat.slug in ('caberawit','muda-mudi') and mm.valid_from<=(now() at time zone 'Asia/Jakarta')::date and (mm.valid_to is null or mm.valid_to>=(now() at time zone 'Asia/Jakarta')::date) and (mm.ended_on is null or mm.ended_on>(now() at time zone 'Asia/Jakarta')::date) order by mm.valid_from desc,mm.id limit 1) placement on true left join public.classes c on c.id=placement.class_id left join public.levels l on l.id=placement.level_id where m.status='ACTIVE' and exists(select 1 from public.member_memberships mc join public.categories cat on cat.id=mc.category_id where mc.member_id=m.id and cat.slug<>'pengurus' and mc.valid_from<=(now() at time zone 'Asia/Jakarta')::date and (mc.ended_on is null or mc.ended_on>(now() at time zone 'Asia/Jakarta')::date) and (mc.valid_to is null or mc.valid_to>=(now() at time zone 'Asia/Jakarta')::date));
 when 'classes' then select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'audience',c.audience,'level_id',c.level_id,'levels',jsonb_build_object('name',l.name)) order by c.name),'[]') into v from public.classes c left join public.levels l on l.id=c.level_id where c.active and c.audience<>'PENGURUS';
 when 'levels' then select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) order by sort_order),'[]') into v from public.levels where active;
 when 'categories' then select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'slug',slug)),'[]') into v from public.categories where slug<>'pengurus';
 when 'attendance' then select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'title',e.title,'event_date',e.event_date,'event_time',e.event_time,'audience',e.audience,'class_id',e.class_id,'level_id',e.level_id,'agenda_id',e.agenda_id,'state',e.state,'classes',jsonb_build_object('name',c.name),'attendance_records',(select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'member_id',r.member_id,'participant_key',r.participant_key,'member_name_snapshot',r.member_name_snapshot,'status',r.status,'class_id_snapshot',r.class_id_snapshot,'class_name_snapshot',r.class_name_snapshot,'level_id_snapshot',r.level_id_snapshot,'level_name_snapshot',r.level_name_snapshot)),'[]') from public.attendance_records r where r.event_id=e.id)) order by e.event_date desc),'[]') into v from public.attendance_events e left join public.classes c on c.id=e.class_id where e.audience<>'PENGURUS';
 when 'agenda' then select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'title',g.title,'starts_at',g.starts_at,'ends_at',g.ends_at,'audience',g.audience,'status',g.status,'presenter',g.presenter,'location',g.location,'class_id',g.class_id,'level_id',g.level_id,'attendance_enabled',g.attendance_enabled,'activity_type_id',g.activity_type_id,'activity_types',jsonb_build_object('name',a.name)) order by starts_at),'[]') into v from public.agenda g left join public.activity_types a on a.id=g.activity_type_id where g.audience<>'PENGURUS';
 when 'journals' then select coalesce(jsonb_agg(jsonb_build_object('id',j.id,'event_id',j.event_id,'journal_date',j.journal_date,'journal_kind',j.journal_kind,'title',j.title,'material',j.material,'summary',j.summary,'achievement',j.achievement,'state',j.state,'class_id',j.class_id,'member_id',j.member_id,'classes',jsonb_build_object('name',c.name),'members',jsonb_build_object('name',m.name),'assessment',jsonb_build_object('materials',coalesce(j.assessment->'materials','[]'::jsonb))) order by journal_date desc),'[]') into v from public.journals j left join public.classes c on c.id=j.class_id left join public.members m on m.id=j.member_id where j.state='COMPLETED' and j.journal_kind<>'PENGURUS' and (j.event_id is null or exists(select 1 from public.attendance_events e where e.id=j.event_id and e.audience<>'PENGURUS' and e.state<>'CANCELLED')) and (j.activity_type_id is null or exists(select 1 from public.activity_types a where a.id=j.activity_type_id and a.audience<>'PENGURUS'));
 when 'targets' then select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'title',t.title,'code',t.code,'target_month',t.target_month,'class_id',t.class_id,'level_id',t.level_id,'version_id',t.version_id,'target_value',t.target_value,'target_unit',t.target_unit,'levels',jsonb_build_object('name',l.name),'classes',jsonb_build_object('name',c.name))),'[]') into v from public.learning_targets t left join public.levels l on l.id=t.level_id left join public.classes c on c.id=t.class_id where t.active;
 when 'versions' then select coalesce(jsonb_agg(jsonb_build_object('id',id,'title',title,'version',version,'period_start',period_start,'period_end',period_end,'created_at',created_at) order by created_at desc),'[]') into v from public.target_versions;
 when 'progress' then select coalesce(jsonb_agg(jsonb_build_object('member_id',coalesce(p.member_id,p.participant_key),'participant_key',p.participant_key,'target_id',p.target_id,'progress_value',p.progress_value,'created_at',p.created_at,'journal_date',j.journal_date)),'[]') into v from public.journal_progress p join public.journals j on j.id=p.journal_id where j.state='COMPLETED' and j.journal_kind in ('CABERAWIT_INDIVIDUAL','MUDA_MUDI_INDIVIDUAL') and (j.event_id is null or exists(select 1 from public.attendance_events e join public.attendance_records r on r.event_id=e.id where e.id=j.event_id and e.state<>'CANCELLED' and r.participant_key=p.participant_key and r.status='H'));
 when 'activity-types' then select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'audience',audience)),'[]') into v from public.activity_types where active and audience<>'PENGURUS';
 when 'report-templates' then v:='[]'::jsonb;
 else raise exception 'Projection non disponible';end case;return v;
end $$;
revoke all on function public.viewer_data(text) from public;grant execute on function public.viewer_data(text) to anon,authenticated;
